### ISSUE TITLE
I'm trying to install and run the example code, but I found I need some extra package.

### ISSUE THREAD

**Issue by mrbeann** [mirri66/xgbmagic#1]
I also install the following package:`unicodecsv` `seaborn`. So I guess this should be mentioned in the installation?

**Comment by mirri66** [comment]
Thank you for spotting that! I've added the extra requirements to the setup file :)

**Comment by mrbeann** [comment]
Actually we often use pip to install it. But it seems it doesn't update yet. so I made a PR for you to update the readme, maybe you can consider it ?

**Comment by mirri66** [comment]
Thanks, this is definitely helpful! I just added the requirements to the setup.py file and bumped the version, so that when people pip install, the requirements should be installed automatically. I'd prefer to minimize the manual installation steps if possible, hence I didn't include the extra instructions in the readme. Hope this works!
